services:
  baste:
    build: .
    container_name: baste
    ports:
      - 9950:9950
    user: 1001:1001
    volumes:
      - /home/services/baste/data:/tmp/baste_storage:z
    environment:
      - BASTE_STORAGE_DIR="/tmp/baste_storage"
      - RUST_LOG=debug
      - BASTE_ADDRESS="0.0.0.0"
